export { InicioPage, DashboardIndexRedirect } from './InicioPage';
export { ServiciosPage } from './ServiciosPage';
export { InventarioPage } from './InventarioPage';
export { OrdenesPage } from './OrdenesPage';
export { NuevaOrdenPage } from './NuevaOrdenPage';
export { OrdenDetallePage } from './OrdenDetallePage';
export { PresupuestosPage } from './PresupuestosPage';
export { NuevaPresupuestoPage } from './NuevaPresupuestoPage';
export { PresupuestoDetallePage } from './PresupuestoDetallePage';
export { GaleriaPage } from './GaleriaPage';
export { ResenasPage } from './ResenasPage';
export { ContenidoPage } from './ContenidoPage';
